### ISSUE TITLE
Add tabs 

### ISSUE THREAD

**Issue by AlbaneMiron** [AlbaneMiron/drone-simulation#24]
Any suggestion on the app structure is welcome.

**Comment by AlbaneMiron** [comment]
https://community.plot.ly/t/new-dash-tabs-component/5780

**Comment by AlbaneMiron** [comment]
@pcorpet J'ai changé les layouts pour insérer des tabs, pour que l'app soit plus claire. 
Mon but est d'arriver à ce rendu là : https://dash-gallery.plotly.host/dash-clustergram/. 

Sauf que mes tabs refusent de se mettre sur le côté, j'ai essayé plein de trucs j'arrive pas à reproduire les tabs comme dans l'application en exemple (je comprends pas où ils spécifient la position de leurs deux Div principales). Aurais tu une idée ? 

Merci beaucoup !

**Comment by pcorpet** [comment]
I don't understand how you want to display your tabs: our current layout is way larger than the little bits there is in ClusterGram. Please provide a quick graph (use Google Slides or whatever you want to draw) that shows what you would like to have, I'll handle the layout.

**Comment by AlbaneMiron** [comment]
I would imagine something like that: 

[layout (glissé(e)s).pdf](https://github.com/AlbaneMiron/drone-simulation/files/3746684/layout.glisse.e.s.pdf)

Parameters selection section is not that wide, I believe it can represent 1/3 of the screen max and still be readable. It should leave enough space for graphs. I may be wrong though. 

Thank you so much for handling the layout.
