### ISSUE TITLE
Simplify parameters

### ISSUE THREAD

**Issue by AlbaneMiron** [AlbaneMiron/drone-simulation#27]
certains paramètres sont tarabiscotés, exemple au lieu du Odd ratio de la détection ACR voie publique à la prise d'appel, tu peux mettre "Rate of OHCA detection by call center operators voie publique" et "Rate of OHCA detection by call center operators lieu privé"

**Comment by AlbaneMiron** [comment]
@clementderkenne @pcorpet je vois l'idée, je comprends que ce paramètre d'odd ratio soit pas très clair mais si je change pour mettre les deux paramètres proposés on perd le lien entre les deux... 
Actuellement on a un taux de détection global et une défaveur voie publique, avec les nouveaux paramètres on aura deux taux de détection VP/domicile complètement indépendants : vous en pensez quoi ?

**Comment by clementderkenne** [comment]
favorable pour que les 2 taux soient séparés: c’est infiniment plus explicite….

**Comment by AlbaneMiron** [comment]
ok, je change ça !

**Comment by AlbaneMiron** [comment]
C fé
