### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by clementderkenne** [AlbaneMiron/drone-simulation#47]
add Paris Fire Brigade and Baye's logo?

**Comment by clementderkenne** [comment]
Don't add until march 2020 please

**Comment by AlbaneMiron** [comment]
Pour la page d’accueil: logo de bayes, de la BSPP, le titre de l’article (que je n’ai pas encore).

**Comment by clementderkenne** [comment]
Standbye until article acceptation.

**Comment by AlbaneMiron** [comment]
done !
