### ISSUE TITLE
change first page

### ISSUE THREAD

**Issue by clementderkenne** [AlbaneMiron/drone-simulation#51]
in the first page, please change

Cette application simule l’envoi de drones  => Ce site internet simule l'envoi de drone
....
porteurs de défibrillateurs automatiques externes (DAE) =>porteurs de défibrillateurs automatiques externes 
....
sur les interventions pour arrêt cardio-respiratoire (ACR) hors milieu hospitalier=> pour les patients en Arrêt Cardio-Respiratoire extrahospitaliers
....
La simulation est basée sur les données => La simulation est basée sur les données réelles
...

des interventions effectuées par la Brigade de Sapeurs Pompiers de Paris (BSPP) => supress (BSPP)

 en petite couronne => et dans les départements limitrophes (Seine Saint Denis, Haut de Seine et Val de Marne)
...
La simulation permet de comparer le temps de présentation hypothétique mis par un drone avec le temps réel de présentation du Véhicule de Secours et d’Assistance aux Victimes (VSAV)=> supress (VSAV)

Cela permet d’estimer quel pourrait être l’impact des drones sur l’amélioration de la chaîne de survie.

L’application permet de faire varier différents paramètres à la fois opérationnels et relatifs aux caractéristiques des drones, et de visualiser leurs impacts sur les temps de présentation. => L'application permet de faire varier différents paramètres: relatifs aux caractéristiques du drone, relatif aux caractéristiques du patient, relatif au caractéristiques de la régulation de l'appel aux secours

**Comment by clementderkenne** [comment]
Add at the end: par défaut, les paramètres des simulations A ou B sont celles qui nous paraissent les plus probables (caractéristiques des drone) ou ceux des performances actuelles de la régulation médicales des sapeurs-pompiers de Paris.

**Comment by AlbaneMiron** [comment]
I don't understand what you mean by "relatif aux caractéristiques du patient"?

**Comment by clementderkenne** [comment]
it concerns bystander alone at home.... but you can delete it if you want.
