### ISSUE TITLE
avoid line breaks

### ISSUE THREAD

**Issue by clementderkenne** [AlbaneMiron/drone-simulation#53]
Avoid line break (like Décalage de détection inconscience/ACR (en s) : )

**Comment by pcorpet** [comment]
There are few ways to get that:
- reduce the font size for those strings
- find smaller strings having the same meaning
- enforce the width to go very large until it fits (but this can be very very large for some text)
- a mix of the above

How do you want me to solve this?

**Comment by clementderkenne** [comment]
The text that is put on the line is very short. I suggest: 
-reduce the size of the text
- pass the "s" just after the box the user fills in = this one is huge, and will never contain more than 2 or 3 numbers. 
- pass the (between 0 and 1) in the tooltips ("when the OHCA is not detected by the dispatcher, no drone is sent; put a rate between 0 and 1").

**Comment by clementderkenne** [comment]
of course, pass the "km", "m/s" also.
