### ISSUE TITLE
space out the figures

### ISSUE THREAD

**Issue by clementderkenne** [AlbaneMiron/drone-simulation#54]
1/ move a little bit down : Intervention distribution figure  and  Time to arrival histogram when a drone is sent

2/ see inserting small separation lines between?

**Comment by AlbaneMiron** [comment]
@pcorpet I cannot figure out how the Sankey graph layout is handled: it behaves mysteriously. Thank you for your help

**Comment by pcorpet** [comment]
@AlbaneMiron The size of the Sankey graph is not fixed as it depends on the sizes of the arrows. I'll add some settings to stabilize it.
