### ISSUE TITLE
change tabs

### ISSUE THREAD

**Issue by clementderkenne** [AlbaneMiron/drone-simulation#56]
When you modify a parameter A or B and click on another tab, it must be as if you had clicked on "start simulation".

**Comment by AlbaneMiron** [comment]
Unsure how to do that. How about putting the 'start simulation" button before parameters selection?

**Comment by clementderkenne** [comment]
can't you do: 
- if you click on a new tab and a parameter has been changed, then start the simulation, otherwise immediately allow the tab change? 
In fact, I'm afraid that visitors will change settings and go to the "comparison" tab without having clicked on the "run simulation" and that they'll tell themselves that nothing has changed....

**Comment by pcorpet** [comment]
@clementderkenne Note that for now the button "Update simulation" is not smart, it's merely recomputing everything not considering whether you've changed a setting or not. Doing that on the tab button would be quite heavy, so I think we should try to be a little smarter. I'll see what I can find.

**Comment by clementderkenne** [comment]
it doesn't work. @pcorpet
