### ISSUE TITLE
pb with aeronautic day

### ISSUE THREAD

**Issue by clementderkenne** [AlbaneMiron/drone-simulation#57]
isn't the aeronautical day control reversed? There is more of a first drone when they can't fly at night.... 
![Capture d’écran 2019-12-10 à 21 11 05](https://user-images.githubusercontent.com/55185234/70565098-b343e300-1b91-11ea-8394-b565d9d447ca.png)
![Capture d’écran 2019-12-10 à 21 11 12](https://user-images.githubusercontent.com/55185234/70565100-b343e300-1b91-11ea-9370-aec7ec30614e.png)

**Comment by AlbaneMiron** [comment]
Fixed it.
