### ISSUE TITLE
Change default OHCA detection rate 

### ISSUE THREAD

**Issue by AlbaneMiron** [AlbaneMiron/drone-simulation#64]
@clementderkenne could you give me the detection rate for OHCA in the streets according to your last publication?

**Comment by clementderkenne** [comment]
on 2017 data it was 0.5
on 2018 it was 0.87.... 

The simulation concerns 2017 so we will say 0.5, but in the article we will explain how important this detection rate on the public road is!

**Comment by AlbaneMiron** [comment]
Ok! And what about the detection rate at home (or in a public place): is it still 0.8?

**Comment by clementderkenne** [comment]
Yes. 
for those looking for the reference: 
https://www.resuscitationjournal.com/article/S0300-9572(19)30692-6/fulltext

**Comment by AlbaneMiron** [comment]
0.87: home
0.71: public place
