### ISSUE TITLE
Same side of favorable parameters of flight restriction graph

### ISSUE THREAD

**Issue by clementderkenne** [AlbaneMiron/drone-simulation#71]
Can you change the order of the boxes on the "flight restriction" graph so that the boxes that are most favorable to flight are always on the same side of the figure? 
ACR detected on the same side as ACR detected, on the same side as enough light on the same side as Day on the same side as drone can flight.

**Comment by AlbaneMiron** [comment]
I wish I could ...

Boxes labels are ordered from the configuration of the first incident. As the configuration is drawn at random from custom parameters values I cannot force a specific configuration (for all set of parameters) for the first incident, thus I cannot force an order for the labels.
